// // Use DBML to define your database structure
// // Docs: https://www.dbml.org/docs

Project products_ve {
  database_type: 'PostgreSQL'
  Note: 'Model for veenezuela product app'
}

Table stores {
  store_id uuid [primary key, default: `uuid_generate_v4 ()`]
  geog GEOGRAPHY(Point) [not null]
  name varchar(255) [not null]
  address TEXT [not null]
  created_at timestamp [not null, default: `now()`]
  updated timestamp [not null, default: `current_timestamp`]
  Note: 'Stores stores locations'
}

Table products {
  product_id uuid [primary key, default: `uuid_generate_v4 ()`]
  name varchar(255) [not null]
  brand varchar(255)
  created_at timestamp [not null, default: `now()`]
  updated timestamp [not null, default: `current_timestamp`]
}

Ref stores_products: stores.store_id <> products.product_id // many-to-many
